GET http://localhost:8080/api/department
Content-Type: application/json; charset=UTF-8

###

GET http://localhost:8080/api/department/1
Content-Type: application/json; charset=UTF-8

###

POST http://localhost:8080/api/department
Content-Type: application/json; charset=UTF-8

{"id":"4", "name": "test4"}

###

DELETE http://localhost:8080/api/department/1
Content-Type: application/json; charset=UTF-8

###